name: Test and lint app

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependies
        run: npm ci
      - name: Lint
        run: npm run lint
