name: Test and lint app

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Print Secrect
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Next.js project
        run: npm run build && npm run export

      - name: List build output for debugging
        run: ls -la out

      - name: Deploy to GitHub page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
